// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLocalization: typeof import('./src/components/TheLocalization.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheOccupation: typeof import('./src/components/TheOccupation.vue')['default']
  }
}
