// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Customers: typeof import('./src/components/Customers.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.8.2/node_modules/iles/dist/client/app/components/Island.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCustomers: typeof import('./src/components/TheCustomers.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLocalization: typeof import('./src/components/TheLocalization.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheOccupation: typeof import('./src/components/TheOccupation.vue')['default']
  }
}
